version: "3"

services:
  mysql:
    container_name: musicplay_db
    image: mysql:8.0.32
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: musicplay_db
