services:
  db:
    container_name: musicplay_db
    image: mysql:8.0.32
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: musicplay_db
    volumes:
      - mysql-data:/var/lib/mysql

  api:
    container_name: musicplay_api
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/musicplay_db
    depends_on:
      - db

  frontend:
    container_name: musicplay_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - api

volumes:
  mysql-data:
